cabal-version:      3.14

name:               mathiassm
version:            0.2.0
build-type:         Simple

license-file:       LICENSE.txt
author:             Mathias San Miguel
maintainer:         mathiassanmiguel@gmail.com
homepage:           https://mathiassm.com

executable site
  main-is:          Main.hs
  hs-source-dirs:   src
  other-modules:    MathiasSM.CleanURL
                  , MathiasSM.Compile
                  , MathiasSM.Context
                  , MathiasSM.Metadata
                  , MathiasSM.Rules.Assets
                  , MathiasSM.Rules.Assets.Favicon
                  , MathiasSM.Rules.PostGroup
                  , MathiasSM.Rules.Redirects
                  , MathiasSM.Rules.Showcase
                  , MathiasSM.Rules.SinglePages
                  , MathiasSM.Rules.Sitemap
  build-depends:    base == 4.*
                  , filepath == 1.5.*
                  , hakyll == 4.17.*
                  , pandoc == 3.12.*
                  , pandoc-types == 1.23.*
                  , tagsoup == 0.14.*
                  , text == 2.1.*
                  , process == 1.6.*
  ghc-options:      -Wall -threaded -rtsopts -with-rtsopts=-N
  default-language: GHC2024
